stages:
  - build

buildJob:
  stage: build
  only:
    - tags
  except:
    - branches
  script:
    - echo "Build container..."
    - docker compose down --rmi all
    - docker compose up -d
    - echo "The container has been completed."
